version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myCloudFormationStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-feq6mjjnpbqx"
s3_prefix = "myCloudFormationStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=827032113985.dkr.ecr.us-east-1.amazonaws.com/mycloudformationstack3ede8fe3/helloworldfunction19d43fc4repo"]
