version: 2
jobs:
    build:
        docker:
            - {image: 'python:3.7.3-stretch'}
        working_directory: ~/repo
        steps:
            - checkout
            - {restore_cache: {keys: ['v1-dependencies-{{ checksum "requirements.txt" }}', v1-dependencies-]}}
            - {run: {name: 'install dependencies', command: "python3 -m venv venv\n. venv/bin/activate\nmake install\nwget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\\\n    chmod +x /bin/hadolint\n"}}
            - {save_cache: {paths: [./venv], key: 'v1-dependencies-{{ checksum "requirements.txt" }}'}}
            - {run: {name: 'run lint', command: ". venv/bin/activate\nmake lint\n"}}